#include <cstdint>
#include <cstddef>
#include <string>
#include <fstream>
#include <iostream>

class CPU
{
public:

    CPU();
    ~CPU();

    bool loadRom(const std::string& filename, uint16_t startAddress = 0x0000);
    void execute(uint8_t opcode, uint8_t op1, uint8_t op2);

    const uint8_t* rom;
    uint8_t* vram;
    uint8_t* ram;

    static const size_t MEMORY_SIZE = 65536;
    static const size_t ROM_SIZE = 8192;
    static const size_t RAM_SIZE = 8192;
    static const size_t VRAM_SIZE = 8192;
    static const size_t OPCODE_NUM = 256;

    uint8_t memory[MEMORY_SIZE];

    struct Registers
    {
        uint8_t A;
        uint8_t B;
        uint8_t C;
        uint8_t D;
        uint8_t E;
        uint8_t H;
        uint8_t L;
    };

    struct Flags
    {
        uint8_t Zero     : 1;
        uint8_t Sign     : 1;
        uint8_t Parity   : 1;
        uint8_t Carry    : 1;
        uint8_t AuxCarry : 1;
    };

    uint16_t PC;
    uint16_t SP;

    Flags flags;
    Registers regs;

    struct Instruction 
    {
        const char* mnemonic;
        uint8_t size;
        uint8_t cycles;
    };

    static const Instruction OpcodeTable[OPCODE_NUM];
};


typedef enum : uint8_t
{
    NOP,
    LXI_B,
    STAX_B,
    INX_B,
    INR_B,
    DCR_B,
    MVI_B,
    RLC,
    UNDEFINED_1,
    DAD_B,
    LDAX_B,
    DCX_B,
    INR_C,
    DCR_C,
    MVI_C,
    RRC,
    UNDEFINED_2,
    LXI_D,
    STAX_D,
    INX_D,
    INR_D,
    DCR_D,
    MVI_D,
    RAL,
    UNDEFINED_3,
    DAD_D,
    LDAX_D,
    DCX_D,
    INR_E,
    DCR_E,
    MVI_E,
    RAR,
    UNDEFINED_4,
    LXI_H,
    SHLD,
    INX_H,
    INR_H,
    DCR_H,
    MVI_H,
    DAA,
    UNDEFINED_5,
    DAD_H,
    LHLD,
    DCX_H,
    INR_L,
    DCR_L,
    MVI_L,
    CMA,
    UNDEFINED_6,
    LXI_SP,
    STA,
    INX_SP,
    INR_M,
    DCR_M,
    MVI_M,
    STC,
    UNDEFINED_7,
    DAD_SP,
    LDA,
    DCX_SP,
    INR_A,
    DCR_A,
    MVI_A,
    CMC,
    MOV_B_B,
    MOV_B_C,
    MOV_B_D,
    MOV_B_E,
    MOV_B_H,
    MOV_B_L,
    MOV_B_M,
    MOV_B_A,
    MOV_C_B,
    MOV_C_C,
    MOV_C_D,
    MOV_C_E,
    MOV_C_H,
    MOV_C_L,
    MOV_C_M,
    MOV_C_A,
    MOV_D_B,
    MOV_D_C,
    MOV_D_D,
    MOV_D_E,
    MOV_D_H,
    MOV_D_L,
    MOV_D_M,
    MOV_D_A,
    MOV_E_B,
    MOV_E_C,
    MOV_E_D,
    MOV_E_E,
    MOV_E_H,
    MOV_E_L,
    MOV_E_M,
    MOV_E_A,
    MOV_H_B,
    MOV_H_C,
    MOV_H_D,
    MOV_H_E,
    MOV_H_H,
    MOV_H_L,
    MOV_H_M,
    MOV_H_A,
    MOV_L_B,
    MOV_L_C,
    MOV_L_D,
    MOV_L_E,
    MOV_L_H,
    MOV_L_L,
    MOV_L_M,
    MOV_L_A,
    MOV_M_B,
    MOV_M_C,
    MOV_M_D,
    MOV_M_E,
    MOV_M_H,
    MOV_M_L,
    HLT,
    MOV_M_A,
    MOV_A_B,
    MOV_A_C,
    MOV_A_D,
    MOV_A_E,
    MOV_A_H,
    MOV_A_L,
    MOV_A_M,
    MOV_A_A,
    ADD_B,
    ADD_C,
    ADD_D,
    ADD_E,
    ADD_H,
    ADD_L,
    ADD_M,
    ADD_A,
    ADC_B,
    ADC_C,
    ADC_D,
    ADC_E,
    ADC_H,
    ADC_L,
    ADC_M,
    ADC_A,
    SUB_B,
    SUB_C,
    SUB_D,
    SUB_E,
    SUB_H,
    SUB_L,
    SUB_M,
    SUB_A,
    SBB_B,
    SBB_C,
    SBB_D,
    SBB_E,
    SBB_H,
    SBB_L,
    SBB_M,
    SBB_A,
    ANA_B,
    ANA_C,
    ANA_D,
    ANA_E,
    ANA_H,
    ANA_L,
    ANA_M,
    ANA_A,
    XRA_B,
    XRA_C,
    XRA_D,
    XRA_E,
    XRA_H,
    XRA_L,
    XRA_M,
    XRA_A,
    ORA_B,
    ORA_C,
    ORA_D,
    ORA_E,
    ORA_H,
    ORA_L,
    ORA_M,
    ORA_A,
    CMP_B,
    CMP_C,
    CMP_D,
    CMP_E,
    CMP_H,
    CMP_L,
    CMP_M,
    CMP_A,
    RNZ,
    PB,
    JNZ,
    JMP,
    CNZ,
    PUSH_B,
    ADI,
    RST_0,
    RZ,
    RET,
    JZ,
    UNDEFINED_8,
    CZ,
    CALL,
    ACI,
    RST_1,
    RNC,
    PD,
    JNC,
    OUT,
    CNC,
    PUSH_D,
    SUI,
    RST_2,
    RC,
    UNDEFINED_9,
    JC,
    IN,
    CC,
    UNDEFINED_10,
    SBI,
    RST_3,
    RPO,
    PH,
    JPO,
    XTHL,
    CPO,
    PUSH_H,
    ANI,
    RST_4,
    RPE,
    PCHL,
    JPE,
    XCHG,
    CPE,
    UNDEFINED_11,
    XRI,
    RST_5,
    RP,
    PPSW,
    JP,
    DI,
    CP,
    PUSH_PSW,
    ORI,
    RST_6,
    RM,
    SPHL,
    JM,
    EI,
    CM,
    EXIT,
    CPI,
    RST_7
} OPCODES;

const CPU::Instruction CPU::OpcodeTable[OPCODE_NUM] = 
{
    [0x00] = { "NOP",         1, 4  },
    [0x01] = { "LXI B",       3, 10 },
    [0x02] = { "STAX B",      1, 7  },
    [0x03] = { "INX B",       1, 5  },
    [0x04] = { "INR B",       1, 5  },
    [0x05] = { "DCR B",       1, 5  },
    [0x06] = { "MVI B",       2, 7  },
    [0x07] = { "RLC",         1, 4  },
    [0x08] = { "UNDEFINED 1", 1, 4  },
    [0x09] = { "DAD B",       1, 10 },
    [0x0A] = { "LDAX B",      1, 7  },
    [0x0B] = { "DCX B",       1, 5  },
    [0x0C] = { "INR C",       1, 5  },
    [0x0D] = { "DCR C",       1, 5  },
    [0x0E] = { "MVI C",       2, 7  },
    [0x0F] = { "RRC",         1, 4  },

    [0x10] = { "UNDEFINED 2", 1, 4  },
    [0x11] = { "LXI D",       3, 10 },
    [0x12] = { "STAX D",      1, 7  },
    [0x13] = { "INX D",       1, 5  },
    [0x14] = { "INR D",       1, 5  },
    [0x15] = { "DCR D",       1, 5  },
    [0x16] = { "MVI D",       2, 7  },
    [0x17] = { "RAL",         1, 4  },
    [0x18] = { "UNDEFINED 3", 1, 4  },
    [0x19] = { "DAD D",       1, 10 },
    [0x1A] = { "LDAX D",      1, 7  },
    [0x1B] = { "DCX D",       1, 5  },
    [0x1C] = { "INR E",       1, 5  },
    [0x1D] = { "DCR E",       1, 5  },
    [0x1E] = { "MVI E",       2, 7  },
    [0x1F] = { "RAR",         1, 4  },

    [0x20] = { "UNDEFINED 4", 1, 4  },
    [0x21] = { "LXI H",       3, 10 },
    [0x22] = { "SHLD",        3, 16 },
    [0x23] = { "INX H",       1, 5  },
    [0x24] = { "INR H",       1, 5  },
    [0x25] = { "DCR H",       1, 5  },
    [0x26] = { "MVI H",       2, 7  },
    [0x27] = { "DAA",         1, 4  },
    [0x28] = { "UNDEFINED 5", 1, 4  },
    [0x29] = { "DAD H",       1, 10 },
    [0x2A] = { "LHLD",        3, 16 },
    [0x2B] = { "DCX H",       1, 5  },
    [0x2C] = { "INR L",       1, 5  },
    [0x2D] = { "DCR L",       1, 5  },
    [0x2E] = { "MVI L",       2, 7  },
    [0x2F] = { "CMA",         1, 4  },

    [0x30] = { "UNDEFINED 6", 1, 4  },
    [0x31] = { "LXI SP",      3, 10 },
    [0x32] = { "STA",         3, 13 },
    [0x33] = { "INX SP",      1, 5  },
    [0x34] = { "INR M",       1, 10 },
    [0x35] = { "DCR M",       1, 10 },
    [0x36] = { "MVI M",       2, 10 },
    [0x37] = { "STC",         1, 4  },
    [0x38] = { "UNDEFINED 7", 1, 4  },
    [0x39] = { "DAD SP",      1, 10 },
    [0x3A] = { "LDA",         3, 13 },
    [0x3B] = { "DCX SP",      1, 5  },
    [0x3C] = { "INR A",       1, 5  },
    [0x3D] = { "DCR A",       1, 5  },
    [0x3E] = { "MVI A",       2, 7  },
    [0x3F] = { "CMC",         1, 4  },

    [0x40] = { "MOV B, B",    1, 5  },
    [0x41] = { "MOV B, C",    1, 5  },
    [0x42] = { "MOV B, D",    1, 5  },
    [0x43] = { "MOV B, E",    1, 5  },
    [0x44] = { "MOV B, H",    1, 5  },
    [0x45] = { "MOV B, L",    1, 5  },
    [0x46] = { "MOV B, M",    1, 7  },
    [0x47] = { "MOV B, A",    1, 5  },
    [0x48] = { "MOV C, B",    1, 5  },
    [0x49] = { "MOV C, C",    1, 5  },
    [0x4A] = { "MOV C, D",    1, 5  },
    [0x4B] = { "MOV C, E",    1, 5  },
    [0x4C] = { "MOV C, H",    1, 5  },
    [0x4D] = { "MOV C, L",    1, 5  },
    [0x4E] = { "MOV C, M",    1, 7  },
    [0x4F] = { "MOV C, A",    1, 5  },

    [0x50] = { "MOV D, B",    1, 5  },
    [0x51] = { "MOV D, C",    1, 5  },
    [0x52] = { "MOV D, D",    1, 5  },
    [0x53] = { "MOV D, E",    1, 5  },
    [0x54] = { "MOV D, H",    1, 5  },
    [0x55] = { "MOV D, L",    1, 5  },
    [0x56] = { "MOV D, M",    1, 7  },
    [0x57] = { "MOV D, A",    1, 5  },
    [0x58] = { "MOV E, B",    1, 5  },
    [0x59] = { "MOV E, C",    1, 5  },
    [0x5A] = { "MOV E, D",    1, 5  },
    [0x5B] = { "MOV E, E",    1, 5  },
    [0x5C] = { "MOV E, H",    1, 5  },
    [0x5D] = { "MOV E, L",    1, 5  },
    [0x5E] = { "MOV E, M",    1, 7  },
    [0x5F] = { "MOV E, A",    1, 5  },

    [0x60] = { "MOV H, B",    1, 5  },
    [0x61] = { "MOV H, C",    1, 5  },
    [0x62] = { "MOV H, D",    1, 5  },
    [0x63] = { "MOV H, E",    1, 5  },
    [0x64] = { "MOV H, H",    1, 5  },
    [0x65] = { "MOV H, L",    1, 5  },
    [0x66] = { "MOV H, M",    1, 7  },
    [0x67] = { "MOV H, A",    1, 5  },
    [0x68] = { "MOV L, B",    1, 5  },
    [0x69] = { "MOV L, C",    1, 5  },
    [0x6A] = { "MOV L, D",    1, 5  },
    [0x6B] = { "MOV L, E",    1, 5  },
    [0x6C] = { "MOV L, H",    1, 5  },
    [0x6D] = { "MOV L, L",    1, 5  },
    [0x6E] = { "MOV L, M",    1, 7  },
    [0x6F] = { "MOV L, A",    1, 5  },

    [0x70] = { "MOV M, B",    1, 7  },
    [0x71] = { "MOV M, C",    1, 7  },
    [0x72] = { "MOV M, D",    1, 7  },
    [0x73] = { "MOV M, E",    1, 7  },
    [0x74] = { "MOV M, H",    1, 7  },
    [0x75] = { "MOV M, L",    1, 7  },
    [0x76] = { "HLT",         1, 7  },
    [0x77] = { "MOV M, A",    1, 7  },
    [0x78] = { "MOV A, B",    1, 5  },
    [0x79] = { "MOV A, C",    1, 5  },
    [0x7A] = { "MOV A, D",    1, 5  },
    [0x7B] = { "MOV A, E",    1, 5  },
    [0x7C] = { "MOV A, H",    1, 5  },
    [0x7D] = { "MOV A, L",    1, 5  },
    [0x7E] = { "MOV A, M",    1, 7  },
    [0x7F] = { "MOV A, A",    1, 5  },

    [0x80] = { "ADD B",       1, 4  },
    [0x81] = { "ADD C",       1, 4  },
    [0x82] = { "ADD D",       1, 4  },
    [0x83] = { "ADD E",       1, 4  },
    [0x84] = { "ADD H",       1, 4  },
    [0x85] = { "ADD L",       1, 4  },
    [0x86] = { "ADD M",       1, 7  },
    [0x87] = { "ADD A",       1, 4  },
    [0x88] = { "ADC B",       1, 4  },
    [0x89] = { "ADC C",       1, 4  },
    [0x8A] = { "ADC D",       1, 4  },
    [0x8B] = { "ADC E",       1, 4  },
    [0x8C] = { "ADC H",       1, 4  },
    [0x8D] = { "ADC L",       1, 4  },
    [0x8E] = { "ADC M",       1, 7  },
    [0x8F] = { "ADC A",       1, 4  },

    [0x90] = { "SUB B",       1, 4  },
    [0x91] = { "SUB C",       1, 4  },
    [0x92] = { "SUB D",       1, 4  },
    [0x93] = { "SUB E",       1, 4  },
    [0x94] = { "SUB H",       1, 4  },
    [0x95] = { "SUB L",       1, 4  },
    [0x96] = { "SUB M",       1, 7  },
    [0x97] = { "SUB A",       1, 4  },
    [0x98] = { "SBB B",       1, 4  },
    [0x99] = { "SBB C",       1, 4  },
    [0x9A] = { "SBB D",       1, 4  },
    [0x9B] = { "SBB E",       1, 4  },
    [0x9C] = { "SBB H",       1, 4  },
    [0x9D] = { "SBB L",       1, 4  },
    [0x9E] = { "SBB M",       1, 7  },
    [0x9F] = { "SBB A",       1, 4  },

    [0xA0] = { "ANA B",       1, 4  },
    [0xA1] = { "ANA C",       1, 4  },
    [0xA2] = { "ANA D",       1, 4  },
    [0xA3] = { "ANA E",       1, 4  },
    [0xA4] = { "ANA H",       1, 4  },
    [0xA5] = { "ANA L",       1, 4  },
    [0xA6] = { "ANA M",       1, 7  },
    [0xA7] = { "ANA A",       1, 4  },
    [0xA8] = { "XRA B",       1, 4  },
    [0xA9] = { "XRA C",       1, 4  },
    [0xAA] = { "XRA D",       1, 4  },
    [0xAB] = { "XRA E",       1, 4  },
    [0xAC] = { "XRA H",       1, 4  },
    [0xAD] = { "XRA L",       1, 4  },
    [0xAE] = { "XRA M",       1, 7  },
    [0xAF] = { "XRA A",       1, 4  },

    [0xB0] = { "ORA B",       1, 4  },
    [0xB1] = { "ORA C",       1, 4  },
    [0xB2] = { "ORA D",       1, 4  },
    [0xB3] = { "ORA E",       1, 4  },
    [0xB4] = { "ORA H",       1, 4  },
    [0xB5] = { "ORA L",       1, 4  },
    [0xB6] = { "ORA M",       1, 7  },
    [0xB7] = { "ORA A",       1, 4  },
    [0xB8] = { "CMP B",       1, 4  },
    [0xB9] = { "CMP C",       1, 4  },
    [0xBA] = { "CMP D",       1, 4  },
    [0xBB] = { "CMP E",       1, 4  },
    [0xBC] = { "CMP H",       1, 4  },
    [0xBD] = { "CMP L",       1, 4  },
    [0xBE] = { "CMP M",       1, 7  },
    [0xBF] = { "CMP A",       1, 4  },

    [0xC0] = { "RNZ",         1, 5  },
    [0xC1] = { "POP B",       1, 10 },
    [0xC2] = { "JNZ",         3, 10 },
    [0xC3] = { "JMP",         3, 10 },
    [0xC4] = { "CNZ",         3, 11 },
    [0xC5] = { "PUSH B",      1, 11 },
    [0xC6] = { "ADI",         2, 7  },
    [0xC7] = { "RST 0",       1, 11 },
    [0xC8] = { "RZ",          1, 5  },
    [0xC9] = { "RET",         1, 10 },
    [0xCA] = { "JZ",          3, 10 },
    [0xCB] = { "UNDEFINED 8", 1, 4  },
    [0xCC] = { "CZ",          3, 11 },
    [0xCD] = { "CALL",        3, 17 },
    [0xCE] = { "ACI",         2, 7  },
    [0xCF] = { "RST 1",       1, 11 },

    [0xD0] = { "RNC",         1, 5  },
    [0xD1] = { "POP D",       1, 10 },
    [0xD2] = { "JNC",         3, 10 },
    [0xD3] = { "OUT",         2, 10 },
    [0xD4] = { "CNC",         3, 11 },
    [0xD5] = { "PUSH D",      1, 11 },
    [0xD6] = { "SUI",         2, 7  },
    [0xD7] = { "RST 2",       1, 11 },
    [0xD8] = { "RC",          1, 5  },
    [0xD9] = { "UNDEFINED 9", 1, 4  },
    [0xDA] = { "JC",          3, 10 },
    [0xDB] = { "IN",          2, 10 },
    [0xDC] = { "CC",          3, 11 },
    [0xDD] = { "UNDEFINED 10",1, 4  },
    [0xDE] = { "SBI",         2, 7  },
    [0xDF] = { "RST 3",       1, 11 },

    [0xE0] = { "RPO",         1, 5  },
    [0xE1] = { "POP H",       1, 10 },
    [0xE2] = { "JPO",         3, 10 },
    [0xE3] = { "XTHL",        1, 18 },
    [0xE4] = { "CPO",         3, 11 },
    [0xE5] = { "PUSH H",      1, 11 },
    [0xE6] = { "ANI",         2, 7  },
    [0xE7] = { "RST 4",       1, 11 },
    [0xE8] = { "RPE",         1, 5  },
    [0xE9] = { "PCHL",        1, 5  },
    [0xEA] = { "JPE",         3, 10 },
    [0xEB] = { "XCHG",        1, 4  },
    [0xEC] = { "CPE",         3, 11 },
    [0xED] = { "UNDEFINED 11",1, 4  },
    [0xEE] = { "XRI",         2, 7  },
    [0xEF] = { "RST 5",       1, 11 },

    [0xF0] = { "RP",          1, 5  },
    [0xF1] = { "POP PSW",     1, 10 },
    [0xF2] = { "JP",          3, 10 },
    [0xF3] = { "DI",          1, 4  },
    [0xF4] = { "CP",          3, 11 },
    [0xF5] = { "PUSH PSW",    1, 11 },
    [0xF6] = { "ORI",         2, 7  },
    [0xF7] = { "RST 6",       1, 11 },
    [0xF8] = { "RM",          1, 5  },
    [0xF9] = { "SPHL",        1, 5  },
    [0xFA] = { "JM",          3, 10 },
    [0xFB] = { "EI",          1, 4  },
    [0xFC] = { "CM",          3, 11 },
    [0xFD] = { "EXIT",        1, 17 },
    [0xFE] = { "CPI",         2, 7  },
    [0xFF] = { "RST 7",       1, 11 }
};